# Generated by Django 2.0.5 on 2018-10-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20181022_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
