# Generated by Django 2.1.2 on 2019-01-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('user', models.CharField(max_length=10)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
