# Generated by Django 2.1.2 on 2019-01-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_question_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
