# Generated by Django 2.1.2 on 2019-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190114_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('login_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='answers',
            name='ans_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
