# Generated by Django 2.1.2 on 2019-02-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190118_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.IntegerField()),
                ('quiz_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='quiz_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizid'),
            preserve_default=False,
        ),
    ]
