# Generated by Django 2.1.2 on 2019-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190217_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.IntegerField(),
        ),
    ]
