# Generated by Django 2.1.3 on 2019-02-20 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20190217_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizid',
            name='ans_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
